# Generated by Django 4.0.6 on 2022-09-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musgame', '0002_game_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('CS', 'Classical'), ('JZ', 'Jazz')], default='CC', max_length=2),
        ),
        migrations.AddField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, upload_to='thumbnails'),
        ),
    ]
