# Generated by Django 4.0.6 on 2022-09-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musgame', '0004_remove_game_photo_alter_game_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, upload_to='mdeia/musgame'),
        ),
    ]
