# Generated by Django 4.0.6 on 2022-09-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musgame', '0007_alter_game_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='html_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='js_content',
            field=models.TextField(blank=True),
        ),
    ]
