# Generated by Django 4.0.6 on 2022-09-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musgame', '0009_alter_game_html_content_alter_game_js_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='html_content',
            field=models.FileField(blank=True, upload_to='musgame/static/musgame/games_html'),
        ),
        migrations.AlterField(
            model_name='game',
            name='js_content',
            field=models.FileField(blank=True, upload_to='musgame/static/musgame/games_js'),
        ),
    ]
