# Generated by Django 4.0.6 on 2022-09-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musgame', '0011_alter_game_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='html_content',
            field=models.FileField(blank=True, upload_to='musgame/templates/musgame/game_html'),
        ),
    ]
