# Generated by Django 4.0.6 on 2022-09-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musgame', '0012_alter_game_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='js_content',
            field=models.FileField(blank=True, upload_to='musgame/static/musgame/game_js'),
        ),
    ]
