# Generated by Django 4.0.6 on 2022-08-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_category_type_alter_category_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category_type',
        ),
    ]
